name: release
on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
permissions: write-all
jobs:
  goreleaser:
    uses: gulfcoastdevops/workflow-templates/.github/workflows/goreleaser-job.yml@main
    with:
      go-version: '>=1.22.0'
    secrets: inherit
  docker:
    needs: goreleaser
    uses: gulfcoastdevops/workflow-templates/.github/workflows/docker-build-push.yml@main
    with:
      image-name: keycloak-operator
      context: ./dist/keycloak-operator_linux_amd64_v1
      dockerfile: ./hack/goreleaser/Dockerfile
      platforms: 'linux/amd64'
    secrets: inherit
